name: release canary
on: workflow_dispatch
jobs:
  release-canary:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: install and build
        run: |
          yarn setup
          yarn build:all
      - name: set npm token
        run: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> ~/.npmrc
      - name: release canary
        run: yarn release:canary
