name: release canary
on: workflow_dispatch
jobs:
  release-canary:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2.2.0
        with:
          node-version: '14'
          cache: 'yarn'
      - name: set npmrc
        run: |
          set -e
          npm config set //registry.npmjs.org/:_authToken=$NPM_TOKEN
        env:
          NPM_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
      - name: install and build
        run: |
          yarn setup
          yarn build:all
      - name: release canary
        run: yarn release:canary
