name: release canary
on: workflow_dispatch
jobs:
  release-canary:
    runs-on: ubuntu-latest
    env:
      NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2.2.0
        with:
          node-version: '14'
          cache: 'yarn'
          registry-url: https://registry.npmjs.org/
          always-auth: true
      - uses: actions/checkout@v2
      - name: Decrypt large secret
        run: ./.github/workflows/decrypt_secret.sh
        env:
          LARGE_SECRET_PASSPHRASE: ${{ secrets.NPM_AUTH_TOKEN }}
      # This command is just an example to show your secret being printed
      # Ensure you remove any print statements of your secrets. GitHub does
      # not hide secrets that use this workaround.
      - name: Test printing your secret (Remove this step in production)
        run: cat $HOME/secrets/my_secret.json
      - name: install and build
        run: |
          yarn setup
          yarn build:all
      - name: release canary
        run: yarn release:canary
