name: release canary
on: workflow_dispatch
jobs:
  release-canary:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.2.0
        with:
          node-version: '14'
      - name: install and build
        run: |
          yarn setup
          yarn build:all
      - name: set npm token
        run: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> ~/.npmrc
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: release canary
        run: yarn release:canary
