# This is a basic workflow that is manually triggered

name: release

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on: workflow_dispatch

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  release:
    runs-on: ubuntu-latest
    env:
      NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
          cache: 'yarn'
          registry-url: https://registry.npmjs.org/
          always-auth: true
      - name: Configure Git User
        run: |
          git config --global user.email "codingzx@gmail.com"
          git config --global user.name "garfish-ci"
      - uses: actions/checkout@v2
      - name: install and build
        run: |
          yarn setup
          yarn build:all
      - name: release
        run: yarn release
